import { defineStore } from "pinia";

export const useGrocery = defineStore("grocery", {
  state: () => ({
    groceryList: [],
    removedIngredients: [],
    // counter: 0,
    filteredIngredients: [],
    newProducts: [],
    //Hardcoded base common ingredients
    commonIngredients: [
      { name: "Salt", category: "Food" },
      { name: "Pepper", category: "Food" },
      { name: "Olive Oil", category: "Food" },
      { name: "Onion", category: "Food" },
      { name: "Garlic", category: "Food" },
      { name: "Tomato", category: "Food" },
      { name: "Chicken", category: "Food" },
      { name: "Beef", category: "Food" },
      { name: "Pasta", category: "Food" },
      { name: "Rice", category: "Food" },
      { name: "Butter", category: "Food" },
      { name: "Milk", category: "Food" },
      { name: "Egg", category: "Food" },
      { name: "Flour", category: "Food" },
      { name: "Sugar", category: "Food" },
      { name: "Baking Powder", category: "Food" },
      { name: "Lemon", category: "Food" },
      { name: "Cumin", category: "Food" },
      { name: "Paprika", category: "Food" },
      { name: "Cilantro", category: "Food" },
      { name: "Basil", category: "Food" },
      { name: "Thyme", category: "Food" },
      { name: "Ginger", category: "Food" },
      { name: "Cinnamon", category: "Food" },
      { name: "Nutmeg", category: "Food" },
      { name: "Lemon Juice", category: "Food" },
      { name: "Honey", category: "Food" },
      { name: "Soy Sauce", category: "Food" },
      { name: "Vinegar", category: "Food" },
      { name: "Chili Powder", category: "Food" },
      { name: "Parmesan Cheese", category: "Food" },
      { name: "Breadcrumbs", category: "Food" },
      { name: "Black Beans", category: "Food" },
      { name: "Bell Pepper", category: "Food" },
      { name: "Carrots", category: "Food" },
      { name: "Celery", category: "Food" },
      { name: "Lime", category: "Food" },
      { name: "Sour Cream", category: "Food" },
      { name: "Cayenne Pepper", category: "Food" },
      { name: "Parsley", category: "Food" },
      { name: "Dill", category: "Food" },
      { name: "Vanilla Extract", category: "Food" },
      { name: "Sesame Oil", category: "Food" },
      { name: "Shrimp", category: "Food" },
      { name: "Salmon", category: "Food" },
      { name: "Lentils", category: "Food" },
      { name: "Peanut Butter", category: "Food" },
      { name: "Mustard", category: "Food" },
      { name: "Mayonnaise", category: "Food" },
      { name: "Tofu", category: "Food" },
      { name: "Quinoa", category: "Food" },
      { name: "Walnuts", category: "Food" },
      { name: "Almonds", category: "Food" },
      { name: "Mushrooms", category: "Food" },
      { name: "Cabbage", category: "Food" },
      { name: "Zucchini", category: "Food" },
      { name: "Broom", category: "Cleaning" },
      { name: "Mop", category: "Cleaning" },
      { name: "Dish Soap", category: "Cleaning" },
      { name: "Bleach", category: "Cleaning" },
      { name: "Laundry Detergent", category: "Cleaning" },
      { name: "Toilet Paper", category: "Cleaning" },
      { name: "Paper Towels", category: "Cleaning" },
      { name: "Trash Bags", category: "Cleaning" },
      { name: "Aluminum Foil", category: "Others" },
      { name: "Plastic Wrap", category: "Others" },
      { name: "Ziplock Bags", category: "Others" },
      { name: "Napkins", category: "Others" },
      { name: "Dishwashing Liquid", category: "Cleaning" },
      { name: "Hand Soap", category: "Cleaning" },
      { name: "Sponges", category: "Cleaning" },
      { name: "Hand Sanitizer", category: "Cleaning" },
      { name: "Trash Can", category: "Cleaning" },
    ],
  }),
});
